GET http://localhost:3001/api/backlogItems/3

###

DELETE http://localhost:3001/api/backlogItems/62bb8e34ebb102e259868136

###

POST http://localhost:3001/api/backlogItems
Content-Type: application/json

{
  "title": "",
  "medium": "Movie"
}

###

PUT http://localhost:3001/api/backlogItems/62bb8e34ebb102e259868136
Content-Type: application/json

{
  "title": "test title 2 test",
  "medium": "Book",
  "progress": false
}