GET http://localhost:3001/api/mediaObjArr/3

###

DELETE http://localhost:3001/api/mediaObjArr/3

###

POST http://localhost:3001/api/mediaObjArr
Content-Type: application/json

{
  "title": "13 Sentinels",
  "medium": "Movie"
}

###

PUT http://localhost:3001/api/mediaObjArr